apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mychart-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: modelosml.local
    http:
      paths:
      {{- range .Values.microservices }}
      - path: {{ .path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .name }}-service
            port:
              number: 80
      {{- end }}

