apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URI
          valueFrom:
            secretKeyRef:
              name: mlflow-secrets
              key: BACKEND_URI
        - name: ARTIFACT_ROOT
          valueFrom:
            secretKeyRef:
              name: mlflow-secrets
              key: ARTIFACT_ROOT
        - name: HOST
          valueFrom:
            secretKeyRef:
              name: mlflow-secrets
              key: HOST
      - name: postgres
        image: postgres:latest
        env:
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_DB
            value: mlflow
        ports:
          - containerPort: 5432